version: 2
updates:
  # Go modules for backend
  - package-ecosystem: "gomod"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "backend:"

  # Go modules for group service
  - package-ecosystem: "gomod" 
    directory: "/backend/services/group"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "group-service:"

  # npm for frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly" 
      day: "monday"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "frontend:"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci:"