services:
  db:
    image: postgres:17.5
    container_name: warikan-db
    environment:
      POSTGRES_DB: warikan
      POSTGRES_USER: warikan
      POSTGRES_PASSWORD: warikan_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U warikan -d warikan"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: warikan-backend
    environment:
      - PORT=8080
      - RUST_LOG=info
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_started
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: warikan-frontend
    environment:
      - VITE_API_MODE=rest
      - VITE_REST_ENDPOINT=http://localhost:8080
      - VITE_API_KEY=dev-api-key-12345
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]

volumes:
  postgres_data:
