// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: settlement/v1/settlement.proto

package settlementv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Balance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	MemberName    string                 `protobuf:"bytes,2,opt,name=member_name,json=memberName,proto3" json:"member_name,omitempty"`
	Amount        float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Balance) Reset() {
	*x = Balance{}
	mi := &file_settlement_v1_settlement_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Balance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Balance) ProtoMessage() {}

func (x *Balance) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_v1_settlement_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Balance.ProtoReflect.Descriptor instead.
func (*Balance) Descriptor() ([]byte, []int) {
	return file_settlement_v1_settlement_proto_rawDescGZIP(), []int{0}
}

func (x *Balance) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *Balance) GetMemberName() string {
	if x != nil {
		return x.MemberName
	}
	return ""
}

func (x *Balance) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Transaction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FromMemberId   string                 `protobuf:"bytes,1,opt,name=from_member_id,json=fromMemberId,proto3" json:"from_member_id,omitempty"`
	FromMemberName string                 `protobuf:"bytes,2,opt,name=from_member_name,json=fromMemberName,proto3" json:"from_member_name,omitempty"`
	ToMemberId     string                 `protobuf:"bytes,3,opt,name=to_member_id,json=toMemberId,proto3" json:"to_member_id,omitempty"`
	ToMemberName   string                 `protobuf:"bytes,4,opt,name=to_member_name,json=toMemberName,proto3" json:"to_member_name,omitempty"`
	Amount         float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_settlement_v1_settlement_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_v1_settlement_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_settlement_v1_settlement_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetFromMemberId() string {
	if x != nil {
		return x.FromMemberId
	}
	return ""
}

func (x *Transaction) GetFromMemberName() string {
	if x != nil {
		return x.FromMemberName
	}
	return ""
}

func (x *Transaction) GetToMemberId() string {
	if x != nil {
		return x.ToMemberId
	}
	return ""
}

func (x *Transaction) GetToMemberName() string {
	if x != nil {
		return x.ToMemberName
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type Settlement struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GroupId               string                 `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Balances              []*Balance             `protobuf:"bytes,3,rep,name=balances,proto3" json:"balances,omitempty"`
	OptimizedTransactions []*Transaction         `protobuf:"bytes,4,rep,name=optimized_transactions,json=optimizedTransactions,proto3" json:"optimized_transactions,omitempty"`
	CalculatedAt          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=calculated_at,json=calculatedAt,proto3" json:"calculated_at,omitempty"`
	IsSettled             bool                   `protobuf:"varint,6,opt,name=is_settled,json=isSettled,proto3" json:"is_settled,omitempty"`
	SettledAt             *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=settled_at,json=settledAt,proto3" json:"settled_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Settlement) Reset() {
	*x = Settlement{}
	mi := &file_settlement_v1_settlement_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settlement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settlement) ProtoMessage() {}

func (x *Settlement) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_v1_settlement_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settlement.ProtoReflect.Descriptor instead.
func (*Settlement) Descriptor() ([]byte, []int) {
	return file_settlement_v1_settlement_proto_rawDescGZIP(), []int{2}
}

func (x *Settlement) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Settlement) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *Settlement) GetBalances() []*Balance {
	if x != nil {
		return x.Balances
	}
	return nil
}

func (x *Settlement) GetOptimizedTransactions() []*Transaction {
	if x != nil {
		return x.OptimizedTransactions
	}
	return nil
}

func (x *Settlement) GetCalculatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CalculatedAt
	}
	return nil
}

func (x *Settlement) GetIsSettled() bool {
	if x != nil {
		return x.IsSettled
	}
	return false
}

func (x *Settlement) GetSettledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SettledAt
	}
	return nil
}

type CalculateSettlementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	RoundingUnit  int32                  `protobuf:"varint,2,opt,name=rounding_unit,json=roundingUnit,proto3" json:"rounding_unit,omitempty"` // 1, 10, 100, 1000
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateSettlementRequest) Reset() {
	*x = CalculateSettlementRequest{}
	mi := &file_settlement_v1_settlement_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateSettlementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateSettlementRequest) ProtoMessage() {}

func (x *CalculateSettlementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_v1_settlement_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateSettlementRequest.ProtoReflect.Descriptor instead.
func (*CalculateSettlementRequest) Descriptor() ([]byte, []int) {
	return file_settlement_v1_settlement_proto_rawDescGZIP(), []int{3}
}

func (x *CalculateSettlementRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *CalculateSettlementRequest) GetRoundingUnit() int32 {
	if x != nil {
		return x.RoundingUnit
	}
	return 0
}

type CalculateSettlementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settlement    *Settlement            `protobuf:"bytes,1,opt,name=settlement,proto3" json:"settlement,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateSettlementResponse) Reset() {
	*x = CalculateSettlementResponse{}
	mi := &file_settlement_v1_settlement_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateSettlementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateSettlementResponse) ProtoMessage() {}

func (x *CalculateSettlementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_v1_settlement_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateSettlementResponse.ProtoReflect.Descriptor instead.
func (*CalculateSettlementResponse) Descriptor() ([]byte, []int) {
	return file_settlement_v1_settlement_proto_rawDescGZIP(), []int{4}
}

func (x *CalculateSettlementResponse) GetSettlement() *Settlement {
	if x != nil {
		return x.Settlement
	}
	return nil
}

type GetSettlementHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken     string                 `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettlementHistoryRequest) Reset() {
	*x = GetSettlementHistoryRequest{}
	mi := &file_settlement_v1_settlement_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettlementHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettlementHistoryRequest) ProtoMessage() {}

func (x *GetSettlementHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_v1_settlement_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettlementHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetSettlementHistoryRequest) Descriptor() ([]byte, []int) {
	return file_settlement_v1_settlement_proto_rawDescGZIP(), []int{5}
}

func (x *GetSettlementHistoryRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GetSettlementHistoryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetSettlementHistoryRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

type GetSettlementHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settlements   []*Settlement          `protobuf:"bytes,1,rep,name=settlements,proto3" json:"settlements,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettlementHistoryResponse) Reset() {
	*x = GetSettlementHistoryResponse{}
	mi := &file_settlement_v1_settlement_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettlementHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettlementHistoryResponse) ProtoMessage() {}

func (x *GetSettlementHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_v1_settlement_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettlementHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetSettlementHistoryResponse) Descriptor() ([]byte, []int) {
	return file_settlement_v1_settlement_proto_rawDescGZIP(), []int{6}
}

func (x *GetSettlementHistoryResponse) GetSettlements() []*Settlement {
	if x != nil {
		return x.Settlements
	}
	return nil
}

func (x *GetSettlementHistoryResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type MarkAsSettledRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SettlementId   string                 `protobuf:"bytes,1,opt,name=settlement_id,json=settlementId,proto3" json:"settlement_id,omitempty"`
	TransactionIds []string               `protobuf:"bytes,2,rep,name=transaction_ids,json=transactionIds,proto3" json:"transaction_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkAsSettledRequest) Reset() {
	*x = MarkAsSettledRequest{}
	mi := &file_settlement_v1_settlement_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsSettledRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsSettledRequest) ProtoMessage() {}

func (x *MarkAsSettledRequest) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_v1_settlement_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsSettledRequest.ProtoReflect.Descriptor instead.
func (*MarkAsSettledRequest) Descriptor() ([]byte, []int) {
	return file_settlement_v1_settlement_proto_rawDescGZIP(), []int{7}
}

func (x *MarkAsSettledRequest) GetSettlementId() string {
	if x != nil {
		return x.SettlementId
	}
	return ""
}

func (x *MarkAsSettledRequest) GetTransactionIds() []string {
	if x != nil {
		return x.TransactionIds
	}
	return nil
}

type MarkAsSettledResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsSettledResponse) Reset() {
	*x = MarkAsSettledResponse{}
	mi := &file_settlement_v1_settlement_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsSettledResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsSettledResponse) ProtoMessage() {}

func (x *MarkAsSettledResponse) ProtoReflect() protoreflect.Message {
	mi := &file_settlement_v1_settlement_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsSettledResponse.ProtoReflect.Descriptor instead.
func (*MarkAsSettledResponse) Descriptor() ([]byte, []int) {
	return file_settlement_v1_settlement_proto_rawDescGZIP(), []int{8}
}

func (x *MarkAsSettledResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_settlement_v1_settlement_proto protoreflect.FileDescriptor

const file_settlement_v1_settlement_proto_rawDesc = "" +
	"\n" +
	"\x1esettlement/v1/settlement.proto\x12\rsettlement.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"_\n" +
	"\aBalance\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12\x1f\n" +
	"\vmember_name\x18\x02 \x01(\tR\n" +
	"memberName\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\"\xd9\x01\n" +
	"\vTransaction\x12$\n" +
	"\x0efrom_member_id\x18\x01 \x01(\tR\ffromMemberId\x12(\n" +
	"\x10from_member_name\x18\x02 \x01(\tR\x0efromMemberName\x12 \n" +
	"\fto_member_id\x18\x03 \x01(\tR\n" +
	"toMemberId\x12$\n" +
	"\x0eto_member_name\x18\x04 \x01(\tR\ftoMemberName\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\"\xd9\x02\n" +
	"\n" +
	"Settlement\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\x122\n" +
	"\bbalances\x18\x03 \x03(\v2\x16.settlement.v1.BalanceR\bbalances\x12Q\n" +
	"\x16optimized_transactions\x18\x04 \x03(\v2\x1a.settlement.v1.TransactionR\x15optimizedTransactions\x12?\n" +
	"\rcalculated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fcalculatedAt\x12\x1d\n" +
	"\n" +
	"is_settled\x18\x06 \x01(\bR\tisSettled\x129\n" +
	"\n" +
	"settled_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tsettledAt\"\\\n" +
	"\x1aCalculateSettlementRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12#\n" +
	"\rrounding_unit\x18\x02 \x01(\x05R\froundingUnit\"X\n" +
	"\x1bCalculateSettlementResponse\x129\n" +
	"\n" +
	"settlement\x18\x01 \x01(\v2\x19.settlement.v1.SettlementR\n" +
	"settlement\"t\n" +
	"\x1bGetSettlementHistoryRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\"\x83\x01\n" +
	"\x1cGetSettlementHistoryResponse\x12;\n" +
	"\vsettlements\x18\x01 \x03(\v2\x19.settlement.v1.SettlementR\vsettlements\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"d\n" +
	"\x14MarkAsSettledRequest\x12#\n" +
	"\rsettlement_id\x18\x01 \x01(\tR\fsettlementId\x12'\n" +
	"\x0ftransaction_ids\x18\x02 \x03(\tR\x0etransactionIds\"1\n" +
	"\x15MarkAsSettledResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xce\x02\n" +
	"\x11SettlementService\x12l\n" +
	"\x13CalculateSettlement\x12).settlement.v1.CalculateSettlementRequest\x1a*.settlement.v1.CalculateSettlementResponse\x12o\n" +
	"\x14GetSettlementHistory\x12*.settlement.v1.GetSettlementHistoryRequest\x1a+.settlement.v1.GetSettlementHistoryResponse\x12Z\n" +
	"\rMarkAsSettled\x12#.settlement.v1.MarkAsSettledRequest\x1a$.settlement.v1.MarkAsSettledResponseB\xc1\x01\n" +
	"\x11com.settlement.v1B\x0fSettlementProtoP\x01ZFgithub.com/jt-chihara/warikan/backend/proto/settlement/v1;settlementv1\xa2\x02\x03SXX\xaa\x02\rSettlement.V1\xca\x02\rSettlement\\V1\xe2\x02\x19Settlement\\V1\\GPBMetadata\xea\x02\x0eSettlement::V1b\x06proto3"

var (
	file_settlement_v1_settlement_proto_rawDescOnce sync.Once
	file_settlement_v1_settlement_proto_rawDescData []byte
)

func file_settlement_v1_settlement_proto_rawDescGZIP() []byte {
	file_settlement_v1_settlement_proto_rawDescOnce.Do(func() {
		file_settlement_v1_settlement_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_settlement_v1_settlement_proto_rawDesc), len(file_settlement_v1_settlement_proto_rawDesc)))
	})
	return file_settlement_v1_settlement_proto_rawDescData
}

var file_settlement_v1_settlement_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_settlement_v1_settlement_proto_goTypes = []any{
	(*Balance)(nil),                      // 0: settlement.v1.Balance
	(*Transaction)(nil),                  // 1: settlement.v1.Transaction
	(*Settlement)(nil),                   // 2: settlement.v1.Settlement
	(*CalculateSettlementRequest)(nil),   // 3: settlement.v1.CalculateSettlementRequest
	(*CalculateSettlementResponse)(nil),  // 4: settlement.v1.CalculateSettlementResponse
	(*GetSettlementHistoryRequest)(nil),  // 5: settlement.v1.GetSettlementHistoryRequest
	(*GetSettlementHistoryResponse)(nil), // 6: settlement.v1.GetSettlementHistoryResponse
	(*MarkAsSettledRequest)(nil),         // 7: settlement.v1.MarkAsSettledRequest
	(*MarkAsSettledResponse)(nil),        // 8: settlement.v1.MarkAsSettledResponse
	(*timestamppb.Timestamp)(nil),        // 9: google.protobuf.Timestamp
}
var file_settlement_v1_settlement_proto_depIdxs = []int32{
	0, // 0: settlement.v1.Settlement.balances:type_name -> settlement.v1.Balance
	1, // 1: settlement.v1.Settlement.optimized_transactions:type_name -> settlement.v1.Transaction
	9, // 2: settlement.v1.Settlement.calculated_at:type_name -> google.protobuf.Timestamp
	9, // 3: settlement.v1.Settlement.settled_at:type_name -> google.protobuf.Timestamp
	2, // 4: settlement.v1.CalculateSettlementResponse.settlement:type_name -> settlement.v1.Settlement
	2, // 5: settlement.v1.GetSettlementHistoryResponse.settlements:type_name -> settlement.v1.Settlement
	3, // 6: settlement.v1.SettlementService.CalculateSettlement:input_type -> settlement.v1.CalculateSettlementRequest
	5, // 7: settlement.v1.SettlementService.GetSettlementHistory:input_type -> settlement.v1.GetSettlementHistoryRequest
	7, // 8: settlement.v1.SettlementService.MarkAsSettled:input_type -> settlement.v1.MarkAsSettledRequest
	4, // 9: settlement.v1.SettlementService.CalculateSettlement:output_type -> settlement.v1.CalculateSettlementResponse
	6, // 10: settlement.v1.SettlementService.GetSettlementHistory:output_type -> settlement.v1.GetSettlementHistoryResponse
	8, // 11: settlement.v1.SettlementService.MarkAsSettled:output_type -> settlement.v1.MarkAsSettledResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_settlement_v1_settlement_proto_init() }
func file_settlement_v1_settlement_proto_init() {
	if File_settlement_v1_settlement_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_settlement_v1_settlement_proto_rawDesc), len(file_settlement_v1_settlement_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_settlement_v1_settlement_proto_goTypes,
		DependencyIndexes: file_settlement_v1_settlement_proto_depIdxs,
		MessageInfos:      file_settlement_v1_settlement_proto_msgTypes,
	}.Build()
	File_settlement_v1_settlement_proto = out.File
	file_settlement_v1_settlement_proto_goTypes = nil
	file_settlement_v1_settlement_proto_depIdxs = nil
}
