run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gosec
    - misspell
    - gocyclo
    - goconst
    - gofmt
    - goimports
    - gomod
    - gomodguard
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - path: "(.+)_test.go"
      linters:
        - goconst
    - path: "internal/(.+)/(.+)_test.go"
      linters:
        - revive
  max-same-issues: 50

output:
  sort-results: true