# Cloudflare Workers configuration for Group Service
name = "warikan-group-service"
main = "bin/server"
compatibility_date = "2024-01-01"

# Environment variables
[vars]
GRPC_PORT = "50051"

# Secrets (set via wrangler secret put)
# DATABASE_URL - Supabase connection string

# Build configuration
[build]
command = "go build -o bin/server ./cmd/server"

# KV namespaces (if needed for caching)
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"

# Service bindings (for internal communication)
[[services]]
binding = "GROUP_SERVICE"
service = "warikan-group-service"