# Cloudflare Workers configuration for GraphQL Gateway
name = "warikan-gateway"
main = "bin/gateway"
compatibility_date = "2024-01-01"

# Environment variables
[vars]
PORT = "8080"
FRONTEND_URLS = "https://warikan.your-domain.com"

# Secrets (set via wrangler secret put)
# FRONTEND_URLS - Can be set as secret for additional security
# ALLOWED_ORIGINS - Additional origins if needed

# Build configuration
[build]
command = "go build -o bin/gateway ./cmd"

# Service bindings for microservices communication
[[services]]
binding = "GROUP_SERVICE"
service = "warikan-group-service"

# Routes configuration
[[routes]]
pattern = "warikan-api.your-domain.com/*"
zone_name = "your-domain.com"