name: Integration Tests

on:
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_DB: warikan
          POSTGRES_USER: warikan
          POSTGRES_PASSWORD: warikan_dev_password
        options: >-
          --health-cmd "pg_isready -U warikan -d warikan"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.5'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h localhost -p 5432 -U warikan -d warikan; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done
        echo "PostgreSQL is ready!"

    - name: Apply database migrations
      working-directory: ./backend
      run: |
        # Install psql for running migrations
        sudo apt-get update
        sudo apt-get install -y postgresql-client
        
        # Apply CI schema (統合版)
        echo "Applying CI schema..."
        PGPASSWORD=warikan_dev_password psql -h localhost -p 5432 -U warikan -d warikan -f "migrations/ci_schema.sql"
        
        # Verify tables were created
        echo "Verifying tables..."
        PGPASSWORD=warikan_dev_password psql -h localhost -p 5432 -U warikan -d warikan -c "\dt"
        
        # Verify schema structure
        echo "Verifying expenses table structure..."
        PGPASSWORD=warikan_dev_password psql -h localhost -p 5432 -U warikan -d warikan -c "\d expenses"
        
        echo "Verifying expense_splits table structure..."
        PGPASSWORD=warikan_dev_password psql -h localhost -p 5432 -U warikan -d warikan -c "\d expense_splits"

    - name: Download Go dependencies
      working-directory: ./backend/services/group
      run: go mod download

    - name: Run integration tests
      working-directory: ./backend/services/group
      env:
        TEST_DATABASE_URL: postgres://warikan:warikan_dev_password@localhost:5432/warikan?sslmode=disable
      run: go test -tags=integration -v ./integration_test.go

    - name: Generate integration test coverage
      working-directory: ./backend/services/group
      env:
        TEST_DATABASE_URL: postgres://warikan:warikan_dev_password@localhost:5432/warikan?sslmode=disable
      run: go test -tags=integration -coverprofile=integration-coverage.out ./integration_test.go

    - name: Upload integration test coverage to Codecov
      if: github.event_name == 'push'
      uses: codecov/codecov-action@v5
      with:
        file: ./backend/services/group/integration-coverage.out
        flags: integration
        name: integration-coverage